parameters:
#    community_element.example.class: Community\Bundle\ElementBundle\Example

services:
#    community_element.example:
#        class: %community_element.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
