parameters:
#    code_code_self.example.class: Code\Bundle\CodeSelfBundle\Example

services:
#    code_code_self.example:
#        class: %code_code_self.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
